### ISSUE TITLE
Suggestion: (result, err) instead of (err, result)

### ISSUE THREAD

**Issue by trusktr** [eugeneware/threadless#1]
Having to check for err everytime can be a little annoying. Make it optional, as the last parameter! f.e.:

``` js
thread.run(30, function (result) {
  expect(result).to.equal(1346269);
});
```

**Comment by eugeneware** [comment]
`(err, result)` is the standard node.js CPS error convention. Changing it would make it more confusing to people who use node.js.

**Comment by trusktr** [comment]
I guess I'm too much browser dev. xD I suppose I can wrap a function around it. :)
